export const PRODUCTS_LOADED = 'PRODUCTS_LOADED';
export const PRODUCT_CHOSEN = 'PRODUCT_CHOSEN';
export const INCREASE_CHOSEN = 'ADD_CHOSEN';
export const DECREASE_CHOSEN = 'ADD_CHOSEN';
export const PRODUCT_DETAIL_LOADED = 'PRODUCT_DETAIL_LOADED';
export const LOADING_FAILED = 'LOADING_FAILED';
export const LOADING_SUCCEEDED = 'LOADING_SUCCEEDED';
